[settings]
experimental = true
env_shell_expand = true # Becomes default soon # https://mise.jdx.dev/environments/#shell-style-variable-expansion
idiomatic_version_file_enable_tools = [ # https://mise.jdx.dev/configuration.html#idiomatic-version-files
    "python",
    "node",
    "yarn",
]
python.uv_venv_auto = "create|source" # https://mise.jdx.dev/lang/python.html#automatic-virtualenv-activation
status.show_env = true

[tasks]
init = 'cp -i "$MISE_TASK_DIR/mise.toml.dist" "$MISE_ORIGINAL_CWD/mise.toml"'
init-member-uv = 'cp -i "$MISE_TASK_DIR/mise.member-uv.toml.dist" "$MISE_ORIGINAL_CWD/mise.toml"'
init-member-poetry = 'cp -i "$MISE_TASK_DIR/mise.member-poetry.toml.dist" "$MISE_ORIGINAL_CWD/mise.toml"'
init-member-pnpm = 'cp -i "$MISE_TASK_DIR/mise.member-pnpm.toml.dist" "$MISE_ORIGINAL_CWD/mise.toml"'

[tasks.debug]
description = "Print task variables."
run = """
echo MISE_ORIGINAL_CWD = $MISE_ORIGINAL_CWD
echo MISE_CONFIG_ROOT = $MISE_CONFIG_ROOT
echo MISE_PROJECT_ROOT = $MISE_PROJECT_ROOT
echo MISE_TASK_NAME = $MISE_TASK_NAME
echo MISE_TASK_DIR = $MISE_TASK_DIR
echo MISE_TASK_FILE = $MISE_TASK_FILE
"""
# End [tasks]


[shell_alias]
rm-deps = "rm -rf .venv"
"bump:patch" = "uv version --bump patch"
"bump:minor" = "uv version --bump minor"
"bump:major" = "uv version --bump major"
# End [shell_alias]


[tools]
node = "latest"
pnpm = "latest"
watchexec = "latest"
uv = "latest"
yarn = "latest"
python = "latest"
poetry = "latest"



[task_templates."uv:sync"]
run = "uv sync"

[task_templates."uv:lock"]
run = "rm -f uv.lock && uv lock"

[task_templates."uv:up"]
run = "mise up; uv python upgrade; uv sync -U"

[task_templates."uv:outdated"]
run = "uv tree --outdated --depth 1 | grep '(latest:' || true" # t6

[task_templates."poetry:sync"]
run = "poetry sync"

[task_templates."poetry:lock"]
run = "poetry lock --regenerate"

[task_templates."poetry:up"]
run = "mise up; poetry update --sync"

[task_templates."poetry:outdated"]
run = "poetry show --outdated"

