[settings]
experimental = true
env_shell_expand = true # Becomes default soon # https://mise.jdx.dev/environments/#shell-style-variable-expansion
idiomatic_version_file_enable_tools = [ # https://mise.jdx.dev/configuration.html#idiomatic-version-files
    "python",
    "node",
    "yarn",
]

# [env]
# https://mise.jdx.dev/environments/

[hooks.enter]
shell = "fish"
script = "load-aliases"

[tasks]
init = 'cp "$MISE_TASK_DIR/mise.toml.dist" "$MISE_ORIGINAL_CWD/mise.toml"'
init-member = 'cp "$MISE_TASK_DIR/mise.member.toml.dist" "$MISE_ORIGINAL_CWD/mise.toml"'

[tasks.debug]
description = "Print task variables."
run = """
echo MISE_ORIGINAL_CWD = $MISE_ORIGINAL_CWD
echo MISE_CONFIG_ROOT = $MISE_CONFIG_ROOT
echo MISE_PROJECT_ROOT = $MISE_PROJECT_ROOT
echo MISE_TASK_NAME = $MISE_TASK_NAME
echo MISE_TASK_DIR = $MISE_TASK_DIR
echo MISE_TASK_FILE = $MISE_TASK_FILE
"""

[tools]
node = "latest"
pnpm = "latest"
watchexec = "latest"
uv = "latest"
yarn = "latest"